//
//  NoisePaint.swift
//  MyNoise
//
//  Created by Kevin Sullivan on 2/19/17.
//  Copyright © 2017 SideApps. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class NoisePaint : NSObject {

    //// Drawing Methods

    public dynamic class func drawPlay(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100), buttonFill: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.00000 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 1.00000 * frame.width, y: frame.minY + 0.50000 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 1.00000 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.00000 * frame.height))
        bezierPath.close()
        buttonFill.setFill()
        bezierPath.fill()
    }

    public dynamic class func drawPause(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100), buttonFill: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)) {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: frame.minX, y: frame.minY, width: 30, height: frame.height))
        buttonFill.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: frame.minX + frame.width - 30, y: frame.minY, width: 30, height: frame.height))
        buttonFill.setFill()
        rectangle2Path.fill()
    }

}
